import {
  Job,
  Company,
  JobSeekerProfile,
  Badge,
  AIRecommendation,
  LiveJobFair,
} from "./types";

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechCorp",
    logo: "/placeholder.svg",
    size: "1000-5000",
    industry: "Technology",
    rating: 4.5,
    reviewsCount: 1234,
    website: "https://techcorp.com",
    description:
      "Leading technology company focused on AI and cloud solutions.",
  },
  {
    id: "2",
    name: "InnovateInc",
    logo: "/placeholder.svg",
    size: "100-500",
    industry: "Software",
    rating: 4.8,
    reviewsCount: 567,
    website: "https://innovateinc.com",
    description: "Fast-growing startup revolutionizing digital experiences.",
  },
  {
    id: "3",
    name: "GrowthCo",
    logo: "/placeholder.svg",
    size: "500-1000",
    industry: "Marketing",
    rating: 4.3,
    reviewsCount: 890,
    website: "https://growthco.com",
    description: "Digital marketing agency helping brands scale globally.",
  },
  {
    id: "4",
    name: "DataFlow Systems",
    logo: "/placeholder.svg",
    size: "2000-5000",
    industry: "Data Analytics",
    rating: 4.6,
    reviewsCount: 2100,
    website: "https://dataflow.com",
    description:
      "Enterprise data analytics and business intelligence solutions.",
  },
  {
    id: "5",
    name: "HealthTech Solutions",
    logo: "/placeholder.svg",
    size: "50-100",
    industry: "Healthcare",
    rating: 4.7,
    reviewsCount: 345,
    website: "https://healthtech.com",
    description: "Innovative healthcare technology improving patient outcomes.",
  },
];

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Full Stack Developer",
    company: mockCompanies[0],
    description:
      "We are looking for an experienced Full Stack Developer to join our AI team. You will work on cutting-edge projects using React, Node.js, and Python.",
    requirements: [
      "5+ years of experience with React and Node.js",
      "Experience with Python and machine learning",
      "Strong understanding of cloud platforms (AWS/GCP)",
      "Excellent problem-solving skills",
    ],
    responsibilities: [
      "Develop and maintain web applications",
      "Collaborate with AI/ML teams",
      "Implement responsive UI components",
      "Optimize application performance",
    ],
    location: {
      city: "San Francisco",
      state: "CA",
      country: "USA",
      coordinates: { lat: 37.7749, lng: -122.4194 },
    },
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "senior",
    salary: {
      min: 120000,
      max: 180000,
      currency: "USD",
      period: "year",
    },
    skills: ["React", "Node.js", "Python", "AWS", "TypeScript"],
    benefits: ["Health Insurance", "Stock Options", "Remote Work", "401k"],
    postedAt: new Date("2024-01-15"),
    applicationDeadline: new Date("2024-02-15"),
    applicationsCount: 45,
    viewsCount: 1234,
    featured: true,
    urgent: false,
    matchScore: 92,
    moodTags: ["innovative", "collaborative", "fast-paced"],
  },
  {
    id: "2",
    title: "Product Marketing Manager",
    company: mockCompanies[2],
    description:
      "Join our marketing team to drive product adoption and growth. You will develop go-to-market strategies and work closely with product teams.",
    requirements: [
      "3+ years in product marketing",
      "Experience with B2B SaaS products",
      "Strong analytical and communication skills",
      "Data-driven approach to marketing",
    ],
    responsibilities: [
      "Develop product positioning and messaging",
      "Create go-to-market strategies",
      "Analyze market trends and competition",
      "Collaborate with sales and product teams",
    ],
    location: {
      city: "New York",
      state: "NY",
      country: "USA",
      coordinates: { lat: 40.7128, lng: -74.006 },
    },
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "mid",
    salary: {
      min: 80000,
      max: 120000,
      currency: "USD",
      period: "year",
    },
    skills: ["Product Marketing", "Analytics", "B2B Sales", "Content Strategy"],
    benefits: [
      "Health Insurance",
      "Unlimited PTO",
      "Learning Budget",
      "Remote Work",
    ],
    postedAt: new Date("2024-01-10"),
    applicationsCount: 23,
    viewsCount: 567,
    featured: false,
    urgent: true,
    matchScore: 78,
    moodTags: ["creative", "data-driven", "strategic"],
  },
  {
    id: "3",
    title: "UX/UI Designer",
    company: mockCompanies[1],
    description:
      "We need a talented designer to create beautiful and functional user experiences for our mobile and web applications.",
    requirements: [
      "3+ years of UX/UI design experience",
      "Proficiency in Figma and design systems",
      "Experience with user research methods",
      "Portfolio showcasing mobile and web designs",
    ],
    responsibilities: [
      "Design user interfaces for web and mobile",
      "Conduct user research and usability testing",
      "Create and maintain design systems",
      "Collaborate with developers and product managers",
    ],
    location: {
      city: "Austin",
      state: "TX",
      country: "USA",
      coordinates: { lat: 30.2672, lng: -97.7431 },
    },
    workMode: "hybrid",
    jobType: "full_time",
    experienceLevel: "mid",
    salary: {
      min: 70000,
      max: 100000,
      currency: "USD",
      period: "year",
    },
    skills: ["Figma", "UX Research", "Prototyping", "Design Systems"],
    benefits: [
      "Health Insurance",
      "Flexible Hours",
      "Design Tools Budget",
      "Gym Membership",
    ],
    postedAt: new Date("2024-01-12"),
    applicationsCount: 67,
    viewsCount: 890,
    featured: true,
    urgent: false,
    matchScore: 85,
    moodTags: ["creative", "user-focused", "collaborative"],
  },
  {
    id: "4",
    title: "Data Scientist",
    company: mockCompanies[3],
    description:
      "Join our data science team to build predictive models and derive insights from large datasets using machine learning techniques.",
    requirements: [
      "MS/PhD in Data Science, Statistics, or related field",
      "Strong Python and SQL skills",
      "Experience with ML frameworks (scikit-learn, TensorFlow)",
      "Knowledge of statistical analysis and visualization",
    ],
    responsibilities: [
      "Build and deploy machine learning models",
      "Analyze large datasets for business insights",
      "Create data visualizations and reports",
      "Collaborate with engineering teams",
    ],
    location: {
      city: "Seattle",
      state: "WA",
      country: "USA",
      coordinates: { lat: 47.6062, lng: -122.3321 },
    },
    workMode: "onsite",
    jobType: "full_time",
    experienceLevel: "mid",
    salary: {
      min: 100000,
      max: 140000,
      currency: "USD",
      period: "year",
    },
    skills: ["Python", "SQL", "Machine Learning", "TensorFlow", "Statistics"],
    benefits: [
      "Health Insurance",
      "Stock Options",
      "Conference Budget",
      "Free Meals",
    ],
    postedAt: new Date("2024-01-08"),
    applicationsCount: 89,
    viewsCount: 1456,
    featured: false,
    urgent: false,
    matchScore: 88,
    moodTags: ["analytical", "innovative", "research-focused"],
  },
  {
    id: "5",
    title: "Frontend Developer",
    company: mockCompanies[4],
    description:
      "Build responsive and accessible user interfaces for our healthcare platform using modern web technologies.",
    requirements: [
      "2+ years of React development experience",
      "Strong HTML, CSS, and JavaScript skills",
      "Experience with accessibility standards",
      "Knowledge of healthcare compliance (HIPAA) preferred",
    ],
    responsibilities: [
      "Develop responsive web applications",
      "Ensure accessibility compliance",
      "Optimize application performance",
      "Work with designers and backend developers",
    ],
    location: {
      city: "Boston",
      state: "MA",
      country: "USA",
      coordinates: { lat: 42.3601, lng: -71.0589 },
    },
    workMode: "remote",
    jobType: "full_time",
    experienceLevel: "entry",
    salary: {
      min: 65000,
      max: 85000,
      currency: "USD",
      period: "year",
    },
    skills: ["React", "JavaScript", "CSS", "Accessibility", "HTML"],
    benefits: [
      "Health Insurance",
      "Remote Work",
      "Learning Budget",
      "Wellness Program",
    ],
    postedAt: new Date("2024-01-14"),
    applicationsCount: 34,
    viewsCount: 678,
    featured: false,
    urgent: true,
    matchScore: 76,
    moodTags: ["mission-driven", "supportive", "learning-oriented"],
  },
];

export const mockBadges: Badge[] = [
  {
    id: "1",
    name: "Profile Complete",
    icon: "✅",
    description: "Completed your profile with all required information",
    earnedAt: new Date("2024-01-01"),
    category: "achievement",
  },
  {
    id: "2",
    name: "Video Resume",
    icon: "🎥",
    description: "Added a video resume to your profile",
    earnedAt: new Date("2024-01-05"),
    category: "achievement",
  },
  {
    id: "3",
    name: "Skill Verified",
    icon: "⭐",
    description: "Completed skill assessment for React",
    earnedAt: new Date("2024-01-10"),
    category: "verification",
  },
  {
    id: "4",
    name: "Active Applicant",
    icon: "🚀",
    description: "Applied to 10+ jobs this month",
    earnedAt: new Date("2024-01-15"),
    category: "activity",
  },
];

export const mockAIRecommendations: AIRecommendation[] = [
  {
    type: "skill_gap",
    title: "Learn TypeScript",
    description:
      "Many of your target jobs require TypeScript. Adding this skill could increase your match rate by 25%.",
    actionUrl: "/learn/typescript",
    priority: "high",
  },
  {
    type: "job_match",
    title: "Perfect Match Found",
    description:
      "We found a Senior Developer role at TechCorp that matches 95% of your criteria.",
    actionUrl: "/jobs/1",
    priority: "high",
  },
  {
    type: "profile_improvement",
    title: "Add Work Experience",
    description:
      "Adding more details about your previous roles could improve your profile score by 15 points.",
    actionUrl: "/profile/experience",
    priority: "medium",
  },
  {
    type: "course",
    title: "AI/ML Fundamentals",
    description:
      "Based on your interests, this course could open up new career opportunities.",
    actionUrl: "/courses/ai-ml",
    priority: "low",
  },
];

export const mockJobFairs: LiveJobFair[] = [
  {
    id: "1",
    title: "Tech Talent Expo 2024",
    description:
      "Connect with top tech companies and startups. Real-time interviews available.",
    startTime: new Date("2024-02-01T10:00:00"),
    endTime: new Date("2024-02-01T18:00:00"),
    companies: [mockCompanies[0], mockCompanies[1], mockCompanies[3]],
    attendeesCount: 1250,
    maxAttendees: 2000,
    tags: ["Technology", "Software", "AI", "Startups"],
    featured: true,
  },
  {
    id: "2",
    title: "Remote Work Summit",
    description: "Discover remote opportunities from companies worldwide.",
    startTime: new Date("2024-02-05T09:00:00"),
    endTime: new Date("2024-02-05T17:00:00"),
    companies: [mockCompanies[2], mockCompanies[4]],
    attendeesCount: 890,
    maxAttendees: 1500,
    tags: ["Remote", "Digital Marketing", "Healthcare"],
    featured: false,
  },
];

export const mockJobSeekerProfile: JobSeekerProfile = {
  id: "1",
  userId: "1",
  title: "Full Stack Developer",
  bio: "Passionate developer with 5 years of experience building scalable web applications. Love working with React, Node.js, and exploring new technologies.",
  skills: ["React", "Node.js", "TypeScript", "Python", "AWS", "MongoDB"],
  experience: [
    {
      id: "1",
      title: "Senior Frontend Developer",
      company: "WebTech Solutions",
      location: "San Francisco, CA",
      startDate: new Date("2022-01-01"),
      endDate: new Date("2024-01-01"),
      current: false,
      description:
        "Led frontend development for multiple client projects using React and TypeScript. Improved application performance by 40% and mentored junior developers.",
    },
    {
      id: "2",
      title: "Full Stack Developer",
      company: "StartupXYZ",
      location: "Remote",
      startDate: new Date("2020-06-01"),
      endDate: new Date("2021-12-31"),
      current: false,
      description:
        "Built the complete web platform from scratch using MERN stack. Implemented real-time features and integrated third-party APIs.",
    },
  ],
  education: [
    {
      id: "1",
      institution: "Stanford University",
      degree: "Master of Science",
      field: "Computer Science",
      startDate: new Date("2018-09-01"),
      endDate: new Date("2020-05-31"),
      grade: "3.8 GPA",
    },
    {
      id: "2",
      institution: "UC Berkeley",
      degree: "Bachelor of Science",
      field: "Computer Science",
      startDate: new Date("2014-09-01"),
      endDate: new Date("2018-05-31"),
      grade: "3.6 GPA",
    },
  ],
  location: {
    city: "San Francisco",
    state: "CA",
    country: "USA",
    coordinates: { lat: 37.7749, lng: -122.4194 },
  },
  preferences: {
    jobTypes: ["full_time", "contract"],
    workModes: ["remote", "hybrid"],
    salaryRange: {
      min: 100000,
      max: 160000,
      currency: "USD",
    },
    industries: ["Technology", "Software", "Fintech"],
    locations: ["San Francisco", "Remote", "New York"],
    commuteTolerance: 30,
  },
  resumeScore: 87,
  videoResumeUrl: "/videos/resume-demo.mp4",
  badges: mockBadges,
  languages: ["English", "Spanish", "Mandarin"],
};
